# Generated by Django 5.0.6 on 2024-06-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_hw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hw',
            options={'verbose_name': 'hw', 'verbose_name_plural': 'hw'},
        ),
        migrations.RemoveField(
            model_name='hw',
            name='status',
        ),
    ]
